CREATE DATABASE IF NOT EXISTS database_data;
USE database_data;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100) UNIQUE
);

CREATE TABLE IF NOT EXISTS friends (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100) UNIQUE,
  age INT(2),
  location VARCHAR(200),
  description VARCHAR(500),
  photoLink VARCHAR(100),
  tags JSON
);

CREATE TABLE IF NOT EXISTS spooners (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100) UNIQUE,
  age INT(2),
  location VARCHAR(200),
  description VARCHAR(500),
  photoLink VARCHAR(100),
  tags JSON
);